// prettier-ignore
const timezoneOptions = [
  { name: '(GMT-12:00) International Date Line West', value: 'Etc/GMT+12' },
  { name: '(GMT-11:00) Coordinated Universal Time-11', value: 'Etc/GMT+11' },
  { name: '(GMT-10:00) Hawaii', value: 'America/Adak' },
  { name: '(GMT-9:30) Marquesas Islands', value: 'Pacific/Marquesas' },
  { name: '(GMT-9:00) Alaska', value: 'America/Anchorage' },
  { name: '(GMT-8:00) Pacific Time (US & Canada)', value: 'America/Dawson_Creek' },
  { name: '(GMT-7:00) Chihuahua, La Paz, Mazatlan', value: 'America/Chihuahua' },
  { name: '(GMT-7:00) Mountain Time (US & Canada)', value: 'America/Denver' },
  { name: '(GMT-6:00) Central Time (US & Canada)', value: 'America/Chicago' },
  { name: '(GMT-6:00) Mexico City', value: 'America/Mexico_City' },
  { name: '(GMT-5:00) Bogota, Lima, Quito, Rio Branco', value: 'America/Bogota' },
  { name: '(GMT-5:00) Eastern Time (US & Canada)', value: 'America/New_York' },
  { name: '(GMT-4:00) Asuncion', value: 'America/Asuncion' },
  { name: '(GMT-4:00) Atlantic Time (Canada)', value: 'Atlantic/Bermuda' },
  { name: '(GMT-4:00) Caracas', value: 'America/Caracas' },
  { name: '(GMT-4:00) Cuiaba', value: 'America/Cuiaba' },
  { name: '(GMT-4:00) Georgetown, La Paz, Manaus, San Juan', value: 'America/Manaus' },
  { name: '(GMT-4:00) Santiago', value: 'America/Santiago' },
  { name: '(GMT-3:30) Newfoundland', value: 'America/St_Johns' },
  { name: '(GMT-3:00) Araguaina', value: 'America/Araguaina' },
  { name: '(GMT-3:00) Brasilia', value: 'America/Sao_Paulo' },
  { name: '(GMT-3:00) Cayenne, Fortaleza', value: '	America/Cayenne' },
  { name: '(GMT-3:00) City of Buenos Aires', value: 'America/Buenos_Aires' },
  { name: '(GMT-2:00) Mid-Atlantic', value: 'America/Noronha' },
  { name: '(GMT-1:00) Azores', value: 'Atlantic/Azores' },
  { name: '(GMT-1:00) Cabo Verde', value: 'Atlantic/Cape_Verde' },
  { name: '(GMT) Western Europe Time, London, Lisbon, Casablanca', value: 'Europe/London' },
  { name: '(GMT+1:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna', value: 'Europe/Amsterdam' },
  { name: '(GMT+1:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague', value: 'Europe/Belgrade' },
  { name: '(GMT+1:00) Brussels, Copenhagen, Madrid, Paris', value: 'Europe/Madrid' },
  { name: '(GMT+1:00) Sarajevo, Skopje, Warsaw, Zagreb', value: 'Europe/Sarajevo' },
  { name: '(GMT+1:00) West Central Africa', value: 'Africa/Lagos' },
  { name: '(GMT+2:00) Amman', value: 'Asia/Amman' },
  { name: '(GMT+2:00) Athens, Bucharest', value: 'Europe/Athens' },
  { name: '(GMT+2:00) Beirut', value: 'Asia/Beirut' },
  { name: '(GMT+2:00) Cairo', value: 'Africa/Cairo' },
  { name: '(GMT+2:00) Chisinau', value: 'Europe/Chisinau' },
  { name: '(GMT+2:00) Damascus', value: 'Asia/Damascus' },
  { name: '(GMT+2:00) Gaza, Hebron', value: 'Asia/Gaza' },
  { name: '(GMT+2:00) Harare, Pretoria', value: 'Africa/Harare' },
  { name: '(GMT+2:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius', value: 'Europe/Helsinki' },
  { name: '(GMT+2:00) Jerusalem', value: 'Asia/Jerusalem' },
  { name: '(GMT+2:00) Juba', value: 'Africa/Juba' },
  { name: '(GMT+2:00) Kaliningrad', value: 'Europe/Kaliningrad' },
  { name: '(GMT+2:00) Khartoum', value: 'Africa/Khartoum' },
  { name: '(GMT+2:00) Tripoli', value: 'Africa/Tripoli' },
  { name: '(GMT+2:00) Windhoek', value: 'Africa/Windhoek' },
  { name: '(GMT+3:00) Baghdad', value: 'Asia/Baghdad' },
  { name: '(GMT+3:00) Istanbul', value: 'Asia/Istanbul' },
  { name: '(GMT+3:00) Kuwait, Riyadh', value: 'Asia/Kuwait' },
  { name: '(GMT+3:00) Minsk', value: 'Europe/Minsk' },
  { name: '(GMT+3:00) Moscow, St.Petersburg', value: 'Europe/Moscow' },
  { name: '(GMT+3:00) Nairobi', value: 'Africa/Nairobi' },
  { name: '(GMT+3:00) Volgograd', value: 'Europe/Volgograd' },
  { name: '(GMT+3:30) Tehran', value: 'Asia/Tehran' },
  { name: '(GMT+4:00) Abu Dhabi, Muscat', value: 'Asia/Muscat' },
  { name: '(GMT+4:00) Astrakhan, Ulyanovsk', value: 'Europe/Astrakhan' },
  { name: '(GMT+4:00) Baku', value: 'Asia/Baku' }, //
  { name: '(GMT+4:00) Izhevsk, Samara', value: 'Europe/Samara' },
  { name: '(GMT+4:00) Saratov', value: 'Europe/Saratov' },
  { name: '(GMT+4:00) Tbilisi', value: 'Asia/Tbilisi' },
  { name: '(GMT+4:00) Yerevan', value: 'Asia/Yerevan' },
  { name: '(GMT+4:30) Kabul', value: 'Asia/Kabul' },
  { name: '(GMT+5:00) Ashgabat, Tashkent', value: 'Asia/Tashkent' },
  { name: '(GMT+5:00) Ekaterinburg', value: 'Asia/Yekaterinburg' },
  { name: '(GMT+5:00) Islamabad, Karachi', value: 'Asia/Karachi' },
  { name: '(GMT+5:00) Qyzylorda', value: 'Asia/Qyzylorda' },
  { name: '(GMT+5:30) Chennai, Kolkata, Mumbai, New Delhi', value: 'Asia/Kolkata' },
  { name: '(GMT+5:45) Kathmandu', value: 'Asia/Katmandu' },
  { name: '(GMT+6:00) Dhaka', value: 'Asia/Dhaka' },
  { name: '(GMT+6:00) Omsk', value: 'Asia/Omsk' },
  { name: '(GMT+6:30) Yangon (Rangoon)', value: 'Asia/Yangon' },
  { name: '(GMT+7:00) Bangkok, Hanoi, Jakarta', value: 'Asia/Bangkok' },
  { name: '(GMT+7:00) Barnaul, Gorno-Altaysk', value: 'Asia/Barnaul' },
  { name: '(GMT+7:00) Hovd', value: 'Asia/Hovd' },
  { name: '(GMT+7:00) Krasnoyarsk', value: 'Asia/Krasnoyarsk' },
  { name: '(GMT+7:00) Novosibirsk', value: 'Asia/Novosibirsk' },
  { name: '(GMT+7:00) Tomsk', value: 'Asia/Tomsk' },
  { name: '(GMT+8:00) Beijing, Chongqing, Hong Kong, Urumqi', value: 'Asia/Hong_Kong' },
  { name: '(GMT+8:00) Irkutsk', value: 'Asia/Irkutsk' },
  { name: '(GMT+8:00) Kuala Lumpur, Singapore', value: 'Asia/Singapore' },
  { name: '(GMT+8:00) Perth', value: 'Australia/Perth' },
  { name: '(GMT+8:00) Taipei', value: 'Asia/Taipei' },
  { name: '(GMT+8:00) Ulaanbaatar', value: 'Asia/Ulaanbaatar' },
  { name: '(GMT+8:45) Eucla', value: 'Australia/Eucla' },
  { name: '(GMT+9:00) Chita', value: 'Asia/Chita' },
  { name: '(GMT+9:00) Osaka, Sapporo, Tokyo', value: 'Asia/Tokyo' },
  { name: '(GMT+9:00) Seoul', value: 'Asia/Seoul' },
  { name: '(GMT+9:00) Yakutsk', value: 'Asia/Yakutsk' },
  { name: '(GMT+9:30) Adelaide, Darwin', value: 'Australia/Adelaide' },
  { name: '(GMT+10:00) Melbourne, Sydney', value: 'Australia/Melbourne' },
  { name: '(GMT+10:00) Guam, Port Moresby', value: 'Pacific/Guam' },
  { name: '(GMT+10:00) Hobart', value: 'Australia/Hobart' },
  { name: '(GMT+10:00) Vladivostok', value: 'Asia/Vladivostok' },
  { name: '(GMT+10:00) Eastern Australia, Guam, Vladivostok', value: 'Antarctica/DumontDUrville' },
  { name: '(GMT+10:30) Lord Howe Island', value: 'Australia/Lord_Howe' },
  { name: '(GMT+11:00) Bougainville Island', value: 'Pacific/Bougainville' },
  { name: '(GMT+11:00) Magadan', value: 'Asia/Magadan' },
  { name: '(GMT+11:00) Norfolk Island', value: 'Pacific/Norfolk' },
  { name: '(GMT+11:00) Sakhalin', value: 'Asia/Sakhalin' },
  { name: '(GMT+12:00) Anadyr, Petropavlovsk-Kamchatsky', value: 'Asia/Anadyr' },
  { name: '(GMT+12:00) Auckland, Wellington', value: 'Pacific/Auckland' },
  { name: '(GMT+12:00) Fiji', value: 'Antarctica/McMurdo' },
  { name: '(GMT+12:45) Chatham Island', value: 'Pacific/Chatham' },
  { name: '(GMT+13:00) Apia, Nukualofa', value: 'Etc/GMT-13' },
  { name: '(GMT+14:00) Kiritimati Island', value: 'Pacific/Kiritimati' },
];

export default timezoneOptions;
