const timezoneOptions = [
  { id: -1, name: '(GMT -12:00) Eniwetok, Kwajalein', value: 'Etc/GMT-12' },
  { id: 0, name: '(GMT -11:00) Midway Island, Samoa', value: 'Pacific/Midway' },
  { id: 1, name: '(GMT -10:00) Hawaii', value: 'America/Adak' },
  { id: 2, name: '(GMT -9:30) Taiohae', value: 'Pacific/Marquesas' },
  { id: 3, name: '(GMT -9:00) Alaska', value: 'America/Anchorage' },
  { id: 4, name: '(GMT -8:00) Pacific Time (US &amp; Canada)', value: 'America/Dawson_Creek' },
  { id: 5, name: '(GMT -7:00) Mountain Time (US &amp; Canada)', value: 'America/Chihuahua' },
  {
    id: 6,
    name: '(GMT -6:00) Central Time (US &amp; Canada), Mexico City',
    value: 'America/Belize',
  },
  {
    id: 7,
    name: '(GMT -5:00) Eastern Time (US &amp; Canada), Bogota, Lima',
    value: 'America/Bogota',
  },
  { id: 8, name: '(GMT -4:30) Caracas', value: 'America/Caracas' },
  {
    id: 9,
    name: '(GMT -4:00) Atlantic Time (Canada), Caracas, La Paz',
    value: 'America/Campo_Grande',
  },
  { id: 10, name: '(GMT -3:30) Newfoundland', value: 'America/St_Johns' },
  { id: 11, name: '(GMT -3:00) Brazil, Buenos Aires, Georgetown', value: 'America/Araguaina' },
  { id: 12, name: '(GMT -2:00) Mid-Atlantic', value: 'America/Noronha' },
  {
    id: 13,
    name: '(GMT -1:00) Azores, Cape Verde Islands',
    value: 'Atlantic/Cape_Verde',
  },
  { id: 14, name: '(GMT) Western Europe Time, London, Lisbon, Casablanca', value: 'Europe/London' },
  { id: 15, name: '(GMT +1:00) Brussels, Copenhagen, Madrid, Paris', value: 'Africa/Algiers' },
  { id: 16, name: '(GMT +2:00) Kaliningrad, South Africa', value: 'Africa/Blantyre' },
  {
    id: 17,
    name: '(GMT +3:00) Baghdad, Riyadh, Moscow, St. Petersburg',
    value: 'Africa/Addis_Ababa',
  },
  { id: 18, name: '(GMT +3:30) Tehran', value: 'Asia/Tehran' },
  { id: 19, name: '(GMT +4:00) Abu Dhabi, Muscat, Baku, Tbilisi', value: 'Asia/Baku' },
  { id: 20, name: '(GMT +4:30) Kabul', value: 'Asia/Kabul' },
  {
    id: 21,
    name: '(GMT +5:00) Ekaterinburg, Islamabad, Karachi, Tashkent',
    value: 'Asia/Tashkent',
  },
  { id: 22, name: '(GMT +5:30) Bombay, Calcutta, Madras, New Delhi', value: 'Asia/Calcutta' },
  { id: 23, name: '(GMT +5:45) Kathmandu, Pokhara', value: 'Asia/Katmandu' },
  { id: 24, name: '(GMT +6:00) Almaty, Dhaka, Colombo', value: '	Asia/Dhaka' },
  { id: 25, name: '(GMT +6:30) Yangon, Mandalay', value: 'Asia/Yangon' },
  { id: 26, name: '(GMT +7:00) Bangkok, Hanoi, Jakarta', value: 'Asia/Ho_Chi_Minh' },
  { id: 27, name: '(GMT +8:00) Beijing, Perth, Singapore, Hong Kong', value: 'Asia/Hong_Kong' },
  { id: 28, name: '(GMT +8:45) Eucla', value: 'Australia/Eucla' },
  { id: 29, name: '(GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk', value: '	Asia/Tokyo' },
  { id: 30, name: '(GMT +9:30) Adelaide, Darwin', value: 'Australia/Adelaide' },
  {
    id: 31,
    name: '(GMT +10:00) Eastern Australia, Guam, Vladivostok',
    value: 'Antarctica/DumontDUrville',
  },
  { id: 32, name: '(GMT +10:30) Lord Howe Island', value: 'Australia/Lord_Howe' },
  { id: 33, name: '(GMT +11:00) Magadan, Solomon Islands, New Caledonia', value: 'Asia/Magadan' },
  {
    id: 35,
    name: '(GMT +12:00) Auckland, Wellington, Fiji, Kamchatka',
    value: 'Antarctica/McMurdo',
  },
  { id: 37, name: '(GMT +13:00) Apia, Nukualofa', value: 'Pacific/Enderbury' },
  { id: 38, name: '(GMT +14:00) Line Islands, Tokelau', value: 'Pacific/Kiritimati0' },
];

export default timezoneOptions;
